type Unit @entity {
  id: ID! @id
  code: String! @column
  name: String! @column
}

type Member @entity {
  id: ID! @id
  number: Int! @column
  givenNames: String! @column
  surname: String! @column
}
