scalar DateTime

type Unit @entity {
  id: ID! @id
  code: String! @column
  name: String! @column
}

type Team @entity {
  id: ID! @id
  unit: String! @column
  name: String! @column
}

type Member @entity {
  id: ID! @id
  number: Int! @column
  givenNames: String! @column
  surname: String! @column
  password: String @column
}

enum StormAvailable {
  AVAILABLE
  UNAVAILABLE
}

enum RescueAvailable {
  IMMEDIATE
  SUPPORT
  UNAVAILABLE
}

type Availability @entity {
  id: ID! @id
  unit: String! @column
  member: Int! @column
  from: DateTime! @column
  to: DateTime! @column
  storm: StormAvailable @column
  rescue: RescueAvailable @column
  vehicle: String @column
  note: String @column
}
