type Unit {
  id: ID!
  code: String!
  name: String!
}

type Member {
  id: ID!
  number: Int!
  fullName: String!
  givenNames: String!
  surname: String!
}

type Query {
  units: [Unit!]!
  members: [Member!]!
}
