scalar DateTime

directive @authenticated on FIELD_DEFINITION

type Unit {
  id: ID!
  code: String!
  name: String!
}

type Member {
  id: ID!
  number: Int!
  fullName: String!
  givenNames: String!
  surname: String!
  availabilities(unitCode: String!, from: DateTime!, to: DateTime!): [Availability!]!
}

enum StormAvailable {
  AVAILABLE
  UNAVAILABLE
}

enum RescueAvailable {
  IMMEDIATE
  SUPPORT
  UNAVAILABLE
}

type Availability {
  id: ID!
  unit: Unit!
  member: Member!
  from: DateTime!
  to: DateTime!
  storm: StormAvailable
  rescue: RescueAvailable
  vehicle: String
  note: String
}

type Query {
  units: [Unit!]! @authenticated

  members: [Member!]! @authenticated
  loggedInMember: Member! @authenticated
}

input AvailabilityInput {
  unitCode: String!
  memberNumber: Int!
  from: DateTime!
  to: DateTime!
  storm: StormAvailable
  rescue: RescueAvailable
  vehicle: String
  note: String
}

type Mutation {
  login(memberNumber: Int!, password: String!): String!
  setAvailability(availability: AvailabilityInput!): [Availability!]!
}
