directive @authenticated on FIELD_DEFINITION

type Unit {
  id: ID!
  code: String!
  name: String!
}

type Member {
  id: ID!
  number: Int!
  fullName: String!
  givenNames: String!
  surname: String!
}

type Query {
  units: [Unit!]! @authenticated

  members: [Member!]! @authenticated
  loggedInMember: Member! @authenticated
}

type Mutation {
  login(memberNumber: Int!, password: String!): String!
}
